.class public abstract Lsa/com/stc/MySTCApplication_HiltComponents$ActivityRetainedC;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements Ldagger/hilt/android/components/ActivityRetainedComponent;
.implements Ldagger/hilt/android/internal/managers/ActivityComponentManager$ActivityComponentBuilderEntryPoint;
.implements Ldagger/hilt/android/internal/managers/HiltWrapper_ActivityRetainedComponentManager_ActivityRetainedLifecycleEntryPoint;
.implements Ldagger/hilt/internal/GeneratedComponent;


# annotations
.annotation runtime Ldagger/Subcomponent;
    modules = {
        Lsa/com/stc/ui/about_stc/AboutStcViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/absher_iam_web_view/AbsherIamWebViewViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/transfer_ownership/accept/AcceptTransferOwnershipViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/add_ons/AddOnsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/my_cart/add_to_cart/AddToCartViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/summary/AddedKeysAndServicesSummaryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/sim_details/AdditionalSimsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/costomizable_offers/AlacartViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/all_devices/AllDevicesViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/number_details/tabs/costs/AllHistoryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/products/viewAllProducts/AllProductsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/replace_sim/anonymous/AnonymousReplaceSIMViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/anonymous_user/AnonymousUserViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/light_mode_select/AppThemePopupViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/bookappointment/AppointmentViewmodel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/auctions/details/summary/AuctionBiddingSummaryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/auctions/categories/AuctionCategoriesViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/auctions/details/AuctionDetailsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/auctions/payment/AuctionPaymentViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/auctions/search/AuctionSearchViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/auctions/AuctionsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/auctions/home/widgets/AuctionsWidgetsViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/balance/viewmodel/BalanceDetailsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/transfer_and_reguest_balance/balance_transfer_amount/BalanceTransferAmountViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/transfer_and_reguest_balance/balance_transfer_summary/BalanceTransferSummaryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/bank_transfer/BankTransferViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/barchart/viewmodel/BartChartViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/base/BaseActivityViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/base/BaseFragmentViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/bill_analytics/BillAnalyticsViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/bill/fragment/details/viewmodel/BillDetailsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/bill_details/BillDetailsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/jawal_control/blacklist_details/BlacklistDetailsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/bring_your_number/current_number_fragment/BringYourNumberCurrentNumberViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/bring_your_number/operator_fragment/BringYourNumberOperatorsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/brows_and_compare_plans/BrowsAndComparePlansViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/subscriptions/viewmodel/BusinessSdkDynamicProductViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/log_details/call_details/CallLogViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/deactivate_your_sim/CancelNumberViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/cash_refund/CashRefundViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_new_landline/landline_change/ChangeNewLandlineViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/change_and_confirmation/change_package/ChangePackageViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/change_package/ChangePostpaidPackageViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/roaming/choose_country/ChooseCountryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/schedule_payment/choose_duration/ChooseDurationViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/choose_nationality/ChooseNationalityViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/choose_number_type/ChooseNumberTypeViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/choose_number/ChooseNumberViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/choose_package_fragment/ChoosePackageViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/wishlist_pickup/ChooseWishListPickupViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/login/choose_your_number/ChooseYourNumberViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/brows_and_compare_plans/compare_bottom_sheet/ComparePackagesBottomSheetViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/products/sawaPlans/CompareSawaPackagesViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/change_and_confirmation/confirmation/ConfirmationViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/contact_us/ContactUsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/contract_blockers_amounts/ContractBlockersViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/devicecontract/ContractsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/number_details/tabs/costs/CostViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/menu/profile/invite_friend/create/CreateInvitationViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/schedule_payment/overview/bottom_sheet/CreditCardBottomSheetViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/customer_support/CustomerSupportHostViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/da_user/DAUserViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/DashBoardViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/dashboard/viewmodel/DashboardViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/login/wifi_da/DataDirectAccessViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/data_sharing/DataSharingViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/send_a_gift/data_sponsor/DataSponsorPackageViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/data_sharing/DataUsageViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/office/DeviceAvailabilityOutletsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/device_details/DeviceBaseViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/devicecontract/viewmodel/DeviceContractViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/device_details/DeviceDetailsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/schedule_payment/direct_payment/DirectPaymentListViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/schedule_payment/direct_payment/DirectPaymentViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/downpayment/DownPaymentOptionsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/downpayment/DownPaymentPayLaterViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/downpayment/DownPaymentViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/econtent/viewmodel/EContentViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/esim/ESimSubscriptionViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/econtent/EcontentViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/entertainment/list_fragment/EntertainmentListViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/entertainment_offer_display/EntertainmentOfferDisplayViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/entertainment/product_display/EntertainmentOverviewViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/stc_wifi/faq/FAQsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/family_plan/FamilyPlanViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/fmc/FixedMobileConvergenceViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/login/forget_password/ForgetPasswordViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/free_sms/viewmodel/FreeSMSViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/friendsandfamily/FriendsAndFamilyViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/gamification/GamificationViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/generic_product_display/GenericProductDisplayViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/gifting_program/GiftingProgramViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/help_center/help_center_starter/HelpCenterStarterViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/help_center/HelpCenterViewModel_HiltModules$KeyModule;,
        Ldagger/hilt/android/internal/managers/HiltWrapper_ActivityRetainedComponentManager_LifecycleModule;,
        Lsa/com/stc/ui/dashboard/home/HomeViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/id_type/IdTypeViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/registration_wizard/idTypes/IdTypesViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/survey/InAppSurveyViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/input_dob/InputDobViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/menu/profile/invite_friend/history/InvitationHistoryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/iot_device_packages/IotDevicePackageViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/jawal_control/JawalControlViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/jawwy_tv/JawwyTVViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/join_stc_home/JoinSTCHomeViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/menu/location_and_converage/location/kiosk/KioskLocationViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/number_properties/number_properties_landline/landline_account/LandlineInternetAccountViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/localnotifications/LocalNotificationsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/locations/LocationsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/logged_in_user/LoggedInUserViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/login/LoginViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/base/LogoutViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/lost_sim/LostSIMViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/product_display_fragment/manage_ringtones/ManageRingtonesViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/manage_sim/ManageSIMViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/maps/map_fragment/MapViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mawjood_extra/MawjoodExtraViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/mawjoodextras/viewmodel/MawjoodExtrasViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/more/MoreViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/multi_sim/MultiSIMViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/my_cart/MyCartViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/MyNumbersAndAllMyContactNumbers/MyNumbersAndAllMyContactNumbersViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/my_orders/rating/MyOrdersRatingViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/my_orders/MyOrdersViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/MySTCApplication_HiltComponents$ActivityCBuilderModule;,
        Lsa/com/stc/MySTCApplication_HiltComponents$ViewModelCBuilderModule;,
        Lsa/com/stc/ui/nafath/NafathViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/new_sim/national_address/NationalAddressViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/partners/nearby_locations/NearbyLocationsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/nearby_recommendations/NearbyRecommendationsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/networkcoverage/NetworkCoverageViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/networkfeedback/NetworkFeedbackViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/notification/fragment/viewmodel/NotificationsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/menu/settings/notifications/NotificationsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/number_details/NumberDetailsViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/number/viewmodel/NumberManagementViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/alFursan/NumberOfPointsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/number_properties/NumberPropertiesViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/numbers_bottom_sheet/NumbersBottomSheetViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/choose_number/NumbersListViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/trade_in_program/offices/OfficesLocationViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/viewmodel/OnBoardingViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/multi_sim/order_multi_sim_purchase/OrderMultiSIMPurchaseViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/number_details/tabs/usage/other_balance/OtherBalanceViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/compose/otp/OtpViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/otp/OtpViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/change_package/fixed_wireless/PackageChangingViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/package_details/PackageDetailsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display_new/PackageOverviewViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/brows_and_compare_plans/bottom_sheet/PackagesBottomSheetViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/paybills/PayBillsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/epayment/PaymentViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/menu/profile/PersonalProfileViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/postpaid_30_day_trial/Postpaid30DayTrialViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/change_package/PostpaidPackagesViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/preferred_language/PreferredLanguageViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/primarynumber/PrimaryNumberViewmodel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/product_display_fragment/ProductDisplayBaseViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/ProductDisplayViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/product_display_fragment/ProductDisplayWithActionViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/subscriptions/viewmodel/ProductsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/add_ons/products/ProductsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/products/ProductsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/store_payment/purchase_device_payment/PurchaseDevicePaymentViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_new_landline/PurchaseNewLandlineViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/free_keys/QitafFreeKeysViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/history/QitafHistoryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/invite_friend/QitafInviteFriendViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/join_qitaf/QitafJoinViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/new_offers/QitafNewOffersViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/partners/tabs/partner_details/QitafPartnerDetailsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/partners/QitafPartnersViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/qr/QitafQRViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/partners/tabs/redeem/QitafRedeemViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/rewards/QitafRewardsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/status_points/QitafStatusPointViewsModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/tire/QitafTireViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/QitafViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/reactivate_account/ReactivateAccountViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/schedule_payment/select_recharge_amount/RechargeAmountViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/number_details/tabs/balance/rechargehistory/RechargeHistoryViewmodel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/recharge/RechargeViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/recommendation/RecommendationViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/reconnect_disconnected_account/ReconnectingDisconnectedAccountViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/registration_wizard/RegistrationWizardViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/replace_sim/logged_in/ReplaceSIMViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/replace_sim/logged_in/replace_sim_summary/ReplaceSimSummaryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/retention_offers/RetentionOffersViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/product_display_fragment/retention_product_display/RetentionProductDisplayViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/roaming/RoamingViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/payment/sawa/viewmodel/SawaRechargeViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/sawa_sponser/SawaSponserViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/scan_mysim/ScanMySimViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/recharge/scan_sawa/ScanSawaViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/schedule_payment/schedule_payment_home/SchedulePaymentHomeViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/schedule_payment/overview/SchedulePaymentOverviewViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/schedule_payment/schedule_payment_pattern/SchedulePaymentPatternViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/schedule_payment/SchedulePaymentViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/search_engine/SearchEngineViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/seasonal_gifts/SeasonalGiftsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/select_contact_number/SelectContactNumberViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/schedule_payment/select_date/SelectDateViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/select_user_number/SelectMyNumberViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/trade_in_program/brands/SelectTradeinBrandViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/recharge/select_voucher/SelectVoucherViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/menu/location_and_converage/location/service_center/ServiceCenterLocationViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/menu/settings/SettingsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_device/shop_by_brand/ShopByBrandViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/sim_details/SimDetailsViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/management/viewmodel/SimManagementViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/new_sim/order_new_sim_summary/SimOrderSummaryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/mysim_services/new_sim/SimOrdersViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/joinstc/choose_simtype/SimTypeViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/sms_inbox/SmsInboxViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/spam_fraud_complaints/SpamFraudComplaintsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/special_offer_display/SpecialOfferDisplayViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/landing/SplashViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/stcplay/StcPlayViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/menu/location_and_converage/location/store/StoreLocationViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/store/StoreViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/store/vouchers/StoreVouchersViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/product_display/fmc/SubscriptionDetailViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/subscriptions/viewmodel/SubscriptionsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/number_details/tabs/subscriptions/SubscriptionsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/support/SupportViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/support/survey/SurveyViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/temporary_disconnection/suspend_landline_temp/SuspendLandlineTemporaryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/temporary_disconnection/suspend_sim_temp/SuspendSimTemporaryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/temporary_disconnection/manage_suspend_landline_temp/tab/SuspensionHistoryViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/qitaf/virtual_cards/TamayouzBenefitsCardViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/tamayouz_gifts/TamayouzGiftViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/purchase_new_landline/technician_visit_date/TechnicianVisitTimeViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/telegram/TelegramViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/terms_and_conditions/TermsAndConditionsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/trade_in_program/book_appointment/TradeInAppointmentViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/trade_in_program/device_specs/TradeInDeviceSpecsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/trade_in_program/TradeInProgramViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/trade_in_program/devices/TradeinDevicesViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/transfer_and_reguest_balance/TransferAndReuestBalanceViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/transfer_ownership/request/TransferOwnershipViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/transfer_and_reguest_balance/requested_balance/TransferRequestedBalanceViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/unlock_device/UnlockDeviceViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/unsettled_amounts/UnsettledViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/dashboard/UpdateContactViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/epayment/UpdateCreditCardViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/update_password/UpdatePasswordViewModel_HiltModules$KeyModule;,
        Lcom/stc/businesssdk/presentation/manage/fragment/usage/viewmodel/UsageDetailsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/log_details/usage_details/UsageDetailsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/number_details/tabs/usage/UsageViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/auctions/userAuctions/UserAuctionsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/menu/user_info/UserInfoViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/user_management/UserManagementViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/verify_email/VerifyViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/voucher_reward/VoucherRewardViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/vouchers_complaints/VouchersComplaintsViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/common/vpn_block/VpnBlockForceUpdateViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/whatsnew/WhatsNewViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/stc_wifi/WifiMapViewModel_HiltModules$KeyModule;,
        Lsa/com/stc/ui/wishlist/WishlistViewModel_HiltModules$KeyModule;
    }
.end annotation

.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lsa/com/stc/MySTCApplication_HiltComponents;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x409
    name = "ActivityRetainedC"
.end annotation

.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lsa/com/stc/MySTCApplication_HiltComponents$ActivityRetainedC$Builder;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 1249
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
